name: Renovate Config Validator

on:
  pull_request:
    paths:
      - '.github/renovate.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: validate renovate.json
        run: npx --package=renovate@43.250.0 -c renovate-config-validator
