name: Renovate Config Validator

on:
  pull_request:
    paths:
      - '.github/renovate.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: validate renovate.json
        run: npx --package=renovate@43.250.0 -c renovate-config-validator
